import {
  project10_site,
  project11_site,
  project12_smm,
  project13_site,
  project14_smm,
  project15_smm,
  project16_site,
  project17_smm,
  project1_smm,
  project2_smm,
  project3_site,
  project4_site,
  project5_smm,
  project6_smm,
  project7_smm,
  project8_smm,
  project9_site,
  project18_smm,
  project19_site,
  project20_site,
  project21_site,
  project22_site,
} from "@/assets/img";

export enum Categories {
  all = "All",
  smm = "SMM",
  sites = "Сайты",
}

interface IprojectsCategories {
  id: number;
  title: Categories;
}

export const projectsCategories: IprojectsCategories[] = [
  {
    id: 1,
    title: Categories.all,
  },
  {
    id: 2,
    title: Categories.smm,
  },
  {
    id: 3,
    title: Categories.sites,
  },
];

export const projects = [
  {
    id: 1,
    img: project10_site,
    title: "РМЦ Калиброн",
    tags: [
      "Исследования",
      "Прототипирование",
      "Дизайн",
      "Разработка",
      "Поддержка",
    ],
    category: Categories.sites,
  },
  {
    id: 2,
    img: project11_site,
    title: "Royal Club",
    tags: [
      "Исследования",
      "Прототипирование",
      "Дизайн",
      "Разработка",
      "Поддержка",
    ],
    category: Categories.sites,
  },
  {
    id: 3,
    img: project12_smm,
    title: "Royal Club",
    tags: [
      "Исследования",
      "Прототипирование",
      "Дизайн",
      "Разработка",
      "Поддержка",
    ],
    category: Categories.smm,
  },
  {
    id: 4,
    img: project13_site,
    title: "Royal Park",
    tags: [
      "Исследования",
      "Прототипирование",
      "Дизайн",
      "Разработка",
      "Поддержка",
    ],
    category: Categories.sites,
  },
  {
    id: 5,
    img: project14_smm,
    title: "Royal Park",
    tags: [
      "Исследования",
      "Прототипирование",
      "Дизайн",
      "Разработка",
      "Поддержка",
    ],
    category: Categories.smm,
  },
  {
    id: 6,
    img: project15_smm,
    title: "StarFood",
    tags: [
      "Исследования",
      "Прототипирование",
      "Дизайн",
      "Разработка",
      "Поддержка",
    ],
    category: Categories.smm,
  },
  {
    id: 7,
    img: project16_site,
    title: "T1 Group",
    tags: [
      "Исследования",
      "Прототипирование",
      "Дизайн",
      "Разработка",
      "Поддержка",
    ],
    category: Categories.sites,
  },
  {
    id: 8,
    img: project17_smm,
    title: "T1 Group",
    tags: [
      "Исследования",
      "Прототипирование",
      "Дизайн",
      "Разработка",
      "Поддержка",
    ],
    category: Categories.smm,
  },
  {
    id: 9,
    img: project1_smm,
    title: "Avansum",
    tags: [
      "Исследования",
      "Прототипирование",
      "Дизайн",
      "Разработка",
      "Поддержка",
    ],
    category: Categories.smm,
  },
  {
    id: 10,
    img: project2_smm,
    title: "Cold Frog",
    tags: [
      "Исследования",
      "Прототипирование",
      "Дизайн",
      "Разработка",
      "Поддержка",
    ],
    category: Categories.smm,
  },
  {
    id: 11,
    img: project3_site,
    title: "DSK",
    tags: [
      "Исследования",
      "Прототипирование",
      "Дизайн",
      "Разработка",
      "Поддержка",
    ],
    category: Categories.sites,
  },
  {
    id: 12,
    img: project4_site,
    title: "JAC",
    tags: [
      "Исследования",
      "Прототипирование",
      "Дизайн",
      "Разработка",
      "Поддержка",
    ],
    category: Categories.sites,
  },
  {
    id: 13,
    img: project5_smm,
    title: "JAC",
    tags: [
      "Исследования",
      "Прототипирование",
      "Дизайн",
      "Разработка",
      "Поддержка",
    ],
    category: Categories.smm,
  },
  {
    id: 14,
    img: project6_smm,
    title: "Кедровый бор",
    tags: [
      "Исследования",
      "Прототипирование",
      "Дизайн",
      "Разработка",
      "Поддержка",
    ],
    category: Categories.smm,
  },
  {
    id: 15,
    img: project7_smm,
    title: "Kross Motors",
    tags: [
      "Исследования",
      "Прототипирование",
      "Дизайн",
      "Разработка",
      "Поддержка",
    ],
    category: Categories.smm,
  },
  {
    id: 16,
    img: project8_smm,
    title: "Лесной двор",
    tags: [
      "Исследования",
      "Прототипирование",
      "Дизайн",
      "Разработка",
      "Поддержка",
    ],
    category: Categories.smm,
  },
  {
    id: 17,
    img: project9_site,
    title: "Miracle Cars",
    tags: [
      "Исследования",
      "Прототипирование",
      "Дизайн",
      "Разработка",
      "Поддержка",
    ],
    category: Categories.sites,
  },
  {
    id: 18,
    img: project18_smm,
    title: "REMBAY",
    tags: [
      "Исследования",
      "Прототипирование",
      "Дизайн",
      "Разработка",
      "Поддержка",
    ],
    category: Categories.smm,
  },
  {
    id: 19,
    img: project19_site,
    title: "ТортБокс",
    tags: [
      "Исследования",
      "Прототипирование",
      "Дизайн",
      "Разработка",
      "Поддержка",
    ],
    category: Categories.sites,
  },
  {
    id: 20,
    img: project20_site,
    title: "ЛидерПласт",
    tags: [
      "Исследования",
      "Прототипирование",
      "Дизайн",
      "Разработка",
      "Поддержка",
    ],
    category: Categories.sites,
  },
  {
    id: 21,
    img: project21_site,
    title: "StarFood",
    tags: [
      "Исследования",
      "Прототипирование",
      "Дизайн",
      "Разработка",
      "Поддержка",
    ],
    category: Categories.sites,
  },
  {
    id: 22,
    img: project22_site,
    title: "Miracle Cars",
    tags: [
      "Исследования",
      "Прототипирование",
      "Дизайн",
      "Разработка",
      "Поддержка",
    ],
    category: Categories.sites,
  },
];
