import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import { MainContextProvider } from "@/context/MainContext";

const jost = Jost({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <MainContextProvider>
        <body className={jost.className}>{children}</body>
      </MainContextProvider>
    </html>
  );
}
